project:                
  type: website          
  output-dir: docs        #- NO TOCAR: carpeta donde se redirige el output
  
website:
  title: "España y sus vecinos"   
  favicon: my_favicon.png           #- pon tu favicon
  # site-url: https://....               #- hay que rellenarlos
  # repo-url: https://....
  # repo-actions: [edit, issue]
  search:   
    location: navbar
    type: overlay   
    copy-button: true
  navbar:
    logo: "my_favicon.png"           #---
    background: "#F5DF61"    #- color de la navbar
    foreground: "#FFFFFF"    #- color navigation elements, text and links that appear in the navbar.
    left: 
      - icon: house-door
        href: index.html
    right:
      - text: "Trabajo en equipo"   #---
        href: my_trabajo_BigData.qmd   
      - text: "Slides"
        href: las_slides_estan.qmd
      - icon: github
        href: https://github.com/AlexMS77   #---
      - icon: twitter
        href: https://twitter.com/<tu-usuario-twitter>  #---
      - icon: envelope
        url: "mailto:<no_escribas@alumni.uv.es>"            #---
  page-footer:
    border: true
    background: "#F5DF61"         #--
    left: "© 2022 Alex, Naira y Luis"   #--
    center: "Hecho con [Quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/AlexMS77 
      - icon: twitter
        href: https://twitter.com/<tu-usuario-twitter>  #-----
      - icon: envelope
        url: "mailto:<tu-mail>@alumni.uv.es"            #-----
    
format:
  html:
    theme: united
    highlight-style: a11y   #-
    css: my_styles.css      #- si queréis añadir cosas
    page-layout: full
    toc: true
    code-copy: true
    code-overflow: wrap    
    code-fold: show
    code-line-numbers: true

# Enable CC licence appendix
#license: "CC BY"

lang: es  

# Default execute options
execute:
  echo: true
  message: false
  warning: false
  eval: true

#- Default knitr options
knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    fig.asp:  7/9
    out.width: "95%"
    fig.align: "center"
    fig.show: "hold"
    R.options:
      options(scipen = 999) #- para quitar la notación científica  
